# Generated by Django 3.0.6 on 2020-06-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.User')),
            ],
        ),
        migrations.CreateModel(
            name='TagXJO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joboffer.JobOffer')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('selected', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Collaborator')),
                ('jo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joboffer.JobOffer')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.User')),
            ],
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Collaborator')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.User')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Collaborator')),
                ('jo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joboffer.JobOffer')),
            ],
        ),
    ]
