# Generated by Django 3.0.6 on 2020-06-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulation',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
